#############################################
# Files required to run Innovation Pipeline #
#############################################

reference_fasta: /Users/johnsoni/Desktop/Resources/Homo_sapiens_assembly19.fasta
reference_fasta_fai: /Users/johnsoni/Desktop/Resources/Homo_sapiens_assembly19.fasta.fai

bqsr__knownSites_dbSNP: {class: File, path: /Users/johnsoni/Desktop/Resources/dbsnp_137.b37.vcf}
bqsr__knownSites_millis: {class: File, path: /Users/johnsoni/Desktop/Resources/Mills_and_1000G_gold_standard.indels.b37.vcf}

# Fingerprinting
FP_config_file: {class: File, path: $PIPELINE_ROOT/resources/fingerprinting/Access_v1_0_curatedSNPs.txt}
