# Files used after standard Bam steps
pool_a_bed_file: {class: File, path: $PIPELINE_ROOT/resources/bedfiles/MSK-ACCESS-v1_0-probe-A.sorted.bed}
pool_b_bed_file: {class: File, path: $PIPELINE_ROOT/resources/bedfiles/MSK-ACCESS-v1_0-probe-B.sorted.bed}

gene_list: {class: File, path: $PIPELINE_ROOT/resources/bedfiles/juber-hg19-gene-list.bed}
