#############################################
# Files required to run Innovation Pipeline #
#############################################

# Used in multiple steps
# Todo: Consolidate
reference_fasta: /ifs/depot/resources/dmp/data/pubdata/hg-fasta/VERSIONS/hg19/Homo_sapiens_assembly19.fasta
reference_fasta_fai: /ifs/depot/resources/dmp/data/pubdata/hg-fasta/VERSIONS/hg19/Homo_sapiens_assembly19.fasta.fai

# BaseRecalibrator
# Todo: Consolidate
bqsr__knownSites_dbSNP: {class: File, path: /ifs/e63data/bergerm1/Resources/DMP/pubdata/dbSNP/VERSIONS/dbsnp_v137/dbsnp_137.b37.vcf}
bqsr__knownSites_millis: {class: File, path: /ifs/e63data/bergerm1/Resources/DMP/pubdata/mills-and-1000g/VERSIONS/v20131014/Mills_and_1000G_gold_standard.indels.b37.vcf}

# Fingerprinting
FP_config_file: {class: File, path: $PIPELINE_ROOT/resources/fingerprinting/Access_v1_0_curatedSNPs.txt}

# UMI QC
A_on_target_positions: {class: File, path: $PIPELINE_ROOT/resources/bedfiles/pan-cancer-panel-v2_2-A-on-target-positions.txt}
B_on_target_positions: {class: File, path: $PIPELINE_ROOT/resources/bedfiles/pan-cancer-panel-v2_2-B-on-target-positions.txt}

# Noise QC
noise__good_positions_A: {class: File, path: /home/johnsoni/Innovation-Pipeline/resources/bedfiles/pan-cancer-panel-v2_2-A-good-positions.txt}
