#########################################
# Files required to run ACCESS Pipeline #
#########################################

# Used in multiple steps
# Todo: Consolidate
reference_fasta: /juno/work/access/production/resources/reference/versions/hg19/Homo_sapiens_assembly19.fasta
reference_fasta_fai: /juno/work/access/production/resources/reference/versions/hg19/Homo_sapiens_assembly19.fasta.fai

# BaseRecalibrator
# Todo: Consolidate
bqsr__knownSites_dbSNP: {class: File, path: /juno/work/access/production/resources/dbSNP/versions/b37/dbsnp_137.b37.vcf}
bqsr__knownSites_millis: {class: File, path: /juno/work/access/production/resources/mills-and-1000g/versions/b37/Mills_and_1000G_gold_standard.indels.b37.vcf}

# Fingerprinting
FP_config_file: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/MSK-ACCESS-v1_0-TilingaAndFpSNPs.txt}

# UMI QC
A_on_target_positions: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/MSK-ACCESS-v1_0-A-on-target-positions.txt}
B_on_target_positions: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/MSK-ACCESS-v1_0-B-on-target-positions.txt}

# Noise QC
noise__good_positions_A: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/MSK-ACCESS-v1_0-A-good-positions.txt}


# Files used after standard Bam steps
#
# Main Bed files (Probe-level)
pool_a_bed_file: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/MSK-ACCESS-v1_0-probe-A.sorted.bed}
pool_b_bed_file: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/MSK-ACCESS-v1_0-probe-B.sorted.bed}
gene_list: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/juber-hg19-gene-list.bed}
# Exon-level Bed file
pool_a_bed_file_exonlevel: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/MSK-ACCESS-v1_0_panelA_canonicaltargets.bed}

# Hotspots
hotspots: {class: File, path: /juno/work/access/production/resources/msk-access/v1.0/regions_of_interest/versions/v1.0/hotspot-list-union-v1-v2_with_TERT.txt}
