language: python
sudo: false
python:
- 2.7
#- 3.4
script: python -m unittest discover -s /Users/johnsoni/Desktop/Code/Innovation-Pipeline/python_tools/test -t /Users/johnsoni/Desktop/Code/Innovation-Pipeline/python_tools/test