language: python
python:
  - '2.7'

install:
  - pip install .

script:
  # Validate CWL
  - find . -name '*.cwl' | xargs -n 1 cwltool --validate
  # Run unit tests
  - cd ./python_tools/test
  - python -m unittest discover -s . -t .

# script:
# - python setup.py install
# cd python_tools/test
# python -m unittest discover
