# Files used after standard Bam steps
pool_a_bed_file: {class: File, path: /home/johnsoni/resources/bedfiles/MSK-ACCESS-v1_0_probe_A.sorted.bed}
pool_b_bed_file: {class: File, path: /home/johnsoni/resources/bedfiles/MSK-ACCESS-v1_0_probe_B.sorted.bed}

gene_list: {class: File, path: /home/johnsoni/resources/bedfiles/juber-hg19-gene-list.bed}
