##########################################
# Default Parameters for ACCESS-Pipeline #
##########################################
tmp_dir: /scratch/

process_loop_umi_fastq__params:
  umi_length: 3
  output_project_folder: .

trimgalore__params:
  length: 25
  paired: true
  gzip: true
  quality: 1
  stringency: 3
  suppress_warn: false

add_or_replace_read_groups__params:
  add_rg_PL: Illumina
  add_rg_CN: BergerLab_MSKCC
  sort_order: coordinate
  validation_stringency: LENIENT
  compression_level: 0
  create_index: true

mark_duplicates__params:
  create_index: true
  assume_sorted: true
  compression_level: 0
  validation_stringency: LENIENT
  duplicate_scoring_strategy: SUM_OF_BASE_QUALITIES

find_covered_intervals__params:
  minbq: 20
  minmq: 20
  cov: 20
  rf: [FailsVendorQualityCheck, BadMate, UnmappedRead, BadCigar]

abra__params:
  kmers: 43,53,63,83,93
  mad: 1000

fix_mate_information__params:
  sort_order: coordinate
  validation_stringency: LENIENT
  compression_level: 0
  create_index: true

base_recalibrator__params:
  nct: 3
  rf: BadCigar

print_reads__params:
  nct: 8
  EOQ: true
  baq: RECALCULATE


#####################################################
# Parameters for Collapsing (module 2.5) & QC steps #
#####################################################

marianas_collapsing__params:
  min_mapping_quality: 1
  min_base_quality: 20
  mismatches: 0
  wobble: 2
  min_consensus_percent: 90

waltz__params:
  coverage_threshold: 50
  min_mapping_quality: 20

########################
# 2nd Realignment step
# Ignore higher base qualities,
# that were changed during collapsing
fci_2__basq_fix: true
