#####################################################
# Parameters for Collapsing (module 2.5) & QC steps #
#####################################################

marianas_collapsing__params:
  min_mapping_quality: 1
  min_base_quality: 20
  mismatches: 1
  wobble: 2
  min_consensus_percent: 90

waltz__params:
  coverage_threshold: 50
  min_mapping_quality: 20

########################
# 2nd Realignment step
# Ignore higher base qualities,
# that were changed during collapsing
fci_2__basq_fix: true
