#####################################################
# Parameters for Collapsing (module 2.5) & QC steps #
#####################################################

############
# Marianas #
############
marianas__min_mapping_quality: 1
marianas__min_base_quality: 30
marianas__mismatches: 1
marianas__wobble: 2
marianas__min_consensus_percent: 90

#########
# Waltz #
#########
coverage_threshold: 50
waltz__min_mapping_quality: 20

########################
# 2nd Realignment step
# Ignore higher base qualities,
# that were changed during collapsing
fci_2__basq_fix: true
