####################################################
# Tool Resource File Paths (for Local development) #
####################################################

run_tools:
  perl_5: /Users/johnsoni/perl5/perlbrew/perls/perl-5.20.2/bin/perl
  java_7: /Library/Java/JavaVirtualMachines/zulu1.7.0_171.jdk/Contents/Home/bin/java
  java_8: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java

  # PLUF & Collapsing
  marianas_path: /Users/johnsoni/Desktop/vendor_tools/Marianas-1.5.jar

  # Module 1
  trimgalore_path: /Users/johnsoni/Desktop/vendor_tools/Trim_Galore_v0.2.5/trim_galore
  bwa_path: /Users/johnsoni/Desktop/vendor_tools/bwa-0.7.5a/bwa
  arrg_path: /Users/johnsoni/Desktop/vendor_tools/AddOrReplaceReadGroups-1.96.jar
  picard_path: /Users/johnsoni/Desktop/vendor_tools/picard-2.8.1.jar

  # Module 2
  gatk_path: /Users/johnsoni/Desktop/vendor_tools/GenomeAnalysisTK.jar
  abra_path: /Users/johnsoni/Desktop/vendor_tools/abra-0.92-SNAPSHOT-jar-with-dependencies--MacSierra.jar
  fx_path: /Users/johnsoni/Desktop/vendor_tools/FixMateInformation.jar

  waltz_path: /Users/johnsoni/Desktop/vendor_tools/Waltz-2.0.jar
