####################################################
# Tool Resource File Paths (for Local development) #
####################################################

# Todo: This is out of date

run_tools:
  perl_5: /Users/johnsoni/perl5/perlbrew/perls/perl-5.20.2/bin/perl
  java_7: /Library/Java/JavaVirtualMachines/zulu1.7.0_171.jdk/Contents/Home/bin/java
  java_8: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java

  # ProcessLoopUMIFastq
  marianas_path: /Users/johnsoni/Desktop/vendor_tools/Marianas-standard.jar

  # Module 1
  trimgalore_path: /Users/johnsoni/Desktop/vendor_tools/Trim_Galore_v0.2.5/trim_galore
  fastqc_path: /Users/johnsoni/Desktop/vendor_tools/FastQC_v0.10.1/fastqc
  cutadapt_path: /Users/johnsoni/Desktop/vendor_tools/cutadapt-1.1/bin/cutadapt
#  cutadapt_path: /Users/johnsoni/Desktop/virtualenv/cwltool_test/bin/cutadapt
  bwa_path: /Users/johnsoni/Desktop/vendor_tools/bwa-0.7.5a/bwa
  arrg_path: /Users/johnsoni/Desktop/vendor_tools/AddOrReplaceReadGroups-1.96.jar
  picard_path: /Users/johnsoni/Desktop/vendor_tools/picard-2.8.1.jar

  # Module 2
  gatk_path: /Users/johnsoni/Desktop/vendor_tools/GenomeAnalysisTK.jar
  #abra_path: /Users/johnsoni/Desktop/vendor_tools/abra-0.92-SNAPSHOT-jar-with-dependencies.jar
  abra_path: /Users/johnsoni/Desktop/vendor_tools/abra-0.92-SNAPSHOT-jar-with-dependencies--MacSierra.jar
  fx_path: /Users/johnsoni/Desktop/vendor_tools/FixMateInformation.jar

  # Module 2.5
  marianas_duplex_path: /Users/johnsoni/Desktop/vendor_tools/Marianas-true-duplex-1-1.jar
  fulcrum_path: /Users/johnsoni/Desktop/vendor_tools/fgbio-0.5.0.jar

  waltz_path: /Users/johnsoni/Desktop/vendor_tools/Waltz-2.0.jar
